
stack:
    - ["Wheel_FL", "Wheel_FR", "Wheel_HR", "Wheel_HL"]
    - ["LeftArm", "RightArm", "Trunk"]
    - ["Postural"]
constraints: ["JointLimits", "VelocityLimits"]

Wheel_FL:
    type: "Cartesian"
    distal_link: "wheel_1"
    base_link: "pelvis"

Wheel_FR:
    type: "Cartesian"
    distal_link: "wheel_2"
    base_link: "pelvis"

Wheel_HL:
    type: "Cartesian"
    distal_link: "wheel_3"
    base_link: "pelvis"

Wheel_HR:
    type: "Cartesian"
    distal_link: "wheel_4"
    base_link: "pelvis"

LeftArm:
    type: "Cartesian"
    distal_link: "arm1_8"
    base_link: "pelvis"
    lambda: 0.1

RightArm:
    type: "Cartesian"
    distal_link: "arm2_8"
    base_link: "pelvis"
    lambda: 0.1
   
Trunk:
    type: "Cartesian"
    distal_link: "pelvis"
    lambda: 0.1

Postural:
    type: "Postural"
    lambda: 0.01
    weight:
        VIRTUALJOINT_1: 0.0
        VIRTUALJOINT_2: 0.0
        VIRTUALJOINT_3: 0.0
        VIRTUALJOINT_4: 0.0
        VIRTUALJOINT_5: 0.0
        VIRTUALJOINT_6: 0.0

    
Com:
    type: "Com"
    lambda: 0.05
    indices: [0, 1]
    weight: 10
